// general analysis options
int isMC_status = 1;
int AASetup_status = 0;
TString jetTreeString = "jetTree";
TString muonTreeString = "muonTree";
TString hltString = "hltTree";
const int NeventFilters = 3;
std::string eventFilters[NeventFilters] = {"pPAprimaryVertexFilter","HBHENoiseFilterResultRun2Loose","pBeamScrapingFilter"};
// options for systematic studies
bool apply_JER_smear = false;
bool apply_JEU_shift_up = false;
bool apply_JEU_shift_down = false;
// options to skip genParticle loops (for forests with no genParticle info)
bool skipGenParticles = false;
// reweighting functions
// pThat cross-section weight (em->weight); false fills every event with weight
// 1, as in PYTHIAHYDJET. Output name: _pThat-<cut> or _pThat-unweighted.
bool doPThatWeight = true;
bool doVzReweight = true;
bool doJetPtReweight = false;
// jet-based filers
bool doGenJetPthatFilter = false;
bool doLeadingXjetDumpFilter = false;
bool doXdumpReweight = false;
bool doJetTrkMaxFilter = true;
bool doRemoveHYDJETjet = true;
bool doEtaPhiMask = false;
bool doPThatCorrelationFilter = true;
// jet-energy alterations
bool doBJetEnergyShift = false;
bool doBJetNeutrinoEnergyShift = false;
bool doNeutrinoEnergyAddition = false;
bool doInclNeutrinoEnergySubtraction = false;
bool apply_genJetPt_smear = false;
bool doJERCorrection = false;
bool doJESCorrection = false;
// muptrel reweight
bool doMuPtRelReweight = false;
bool doHadronPtRelReweight = false;
bool doHadronPtRelReweightToMuon = false;
bool doDRReweight = false;
bool doWeightCut = false;
bool doJetAxisSmearing = false;
bool doWDecayFilter = true;
// select dataset
bool doDiJetSample = true;
// stuff for dataset naming
TString generator = "PYTHIA";
// jet-axis smearing parameters
double mu_phi = 0.0;
double sigma_phi = 0.005;
double mu_eta = 0.0;
double sigma_eta = 0.005;
// Multi-sigma jet-axis smearing scan (PYTHIA_scan.C). On top of the nominal
// templates, the muon ptRel templates are refilled with the reco jet axis
// smeared by each sigma below, the SAME sigma in eta and in phi, nominal jet pT
// only. One standard-normal (eta, phi) offset is drawn per jet and scaled by
// each sigma, so neighbouring sigmas differ only by the smearing, not by noise.
// Purpose: pp templates with the axis smeared to PbPb-like resolution, the
// sigma fixed per centrality class and jet-pT window by matching the
// PYTHIA+HYDJET b and c templates and then applied to light (whose PbPb MC
// statistics are too thin). Output names ..._<flavor>_axisSmear<k>; the sigmas
// are stored as h_axisSmearSigma. Tagged _axisSmearScan.
bool doAxisSmearScan = true;
const int NAxisSmear = 9;
const double axisSmearSigma[NAxisSmear] = {0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.08, 0.10};
// triggers
bool applyJet60Trigger = false;
bool applyJet80Trigger = false;
bool applyJet100Trigger = false;
bool applyMu12TriggerEfficiencyCorrection = false;
bool applyMu5Jet30Trigger = false;
bool applyMu5Jet40Trigger = false;
bool applyMu5Jet60Trigger = false;
bool fillMu5 = false;
bool fillMu7 = false;
bool fillMu12 = true;
// jet mods
bool useCaloJetsOverride = false;
bool useManualJEC = true;
// PF jets only: drop every reco PF jet with no ak4Calo jet within dR < 0.2
// (src/scanning/scan_calo_jet_match.h). Applies to ALL reco-jet histograms and
// the muon tag; event counts and gen-level histograms are unaffected. The scan
// aborts if the forest has no calo tree. Adds _caloJetMatched to the output name.
bool requireCaloJetMatch = false;
// "reverse unfolding" (2026-10-08), PYTHIA_scan_response.C only: an EVENT weight
// at the leading muon-tagged reco jet's pT, the pp b-jet data / PYTHIA reco ratio
// (headers/fitParameters/leadMuTagEventWeight_PYTHIA_PF.h, generated by
// src/calculateBJetsPerZ/reverseUnfoldReweight_PF_pp.C). Adds
// _leadMuTagEventReweight to the response file name.
bool doLeadMuTagEventReweight = true;
// for the response scan: keep only even- or odd-indexed events, giving the two
// statistically independent halves unfoldClosureTest.C trains and tests on
bool onlyEvenEvents = false;
bool onlyOddEvents = false;
// response scan: fill only jets whose jet-branch muon (mupt/mueta, no
// muon-tree matching) passes muPtCut and |eta| < 2
bool onlyMuTaggedJets = false;


