#pragma once
// Event weight for the PYTHIA response scan's "reverse unfolding"
// (PYTHIA_scan_response.C, config_PYTHIA.h: doLeadMuTagEventReweight).
// GENERATED by src/calculateBJetsPerZ/reverseUnfoldReweight_PF_pp.C(true)
// on 2026-10-8 -- do not edit by hand, rerun the macro.
//
// w(pT) = (pT/100)^s: the per-jet pp b data / PYTHIA reco ratio (meas = muon-tagged
// x purity, PF chain) fitted on reco 70-300 GeV, normalized to 1 at 100 GeV (the
// consumer rescales the reweighted response so its reco matches the data).
// pT is clamped to [20, 300]: below 70 GeV the weight is the fit EXTRAPOLATED.
// Fitted against the response PYTHIA_DiJet_response_pThat-15_mu12_pTmu-15_tight_vzReweight_jetTrkMaxFilter_removeHYDJETjet0p35CutOnGen_2026-2-18_muTaggedJetsNoTrigger.root;
// check the rescan's reweighted reco against the data and iterate if it does not match.
#include <cmath>
#include <algorithm>
const double leadMuTagEWpp_s = 0.200940;
const double leadMuTagEWpp_ptLo = 20.0, leadMuTagEWpp_ptHi = 300.0;
inline double leadMuTagEventWeightPP(double pt){
  if(pt <= 0.) return 1.;
  return std::pow(std::min(leadMuTagEWpp_ptHi, std::max(leadMuTagEWpp_ptLo, pt))/100., leadMuTagEWpp_s);
}
