#pragma once
// Event weight for the PYTHIA+HYDJET response scan's "reverse unfolding"
// (PYTHIAHYDJET_scan_response.C, config_PYTHIAHYDJET.h: doLeadMuTagEventReweight).
// GENERATED by src/calculateBJetsPerZ/reverseUnfoldReweight_PF_PbPb.C("pow", true)
// on 2026-10-8 -- do not edit by hand, rerun the macro.
//
// w(pT) = (pT/100)^(s + t ln(pT/100)): the per-jet PbPb b data / MC reco ratio
// (meas = muon-tagged x purity, PF chain) fitted on reco 70-300 GeV, normalized
// to 1 at 100 GeV (the scan's absolute normalization is not the fit's: the
// consumer rescales the reweighted response so its reco matches the data).
// pT is clamped to [20, 300]: below 70 GeV the weight is the fit EXTRAPOLATED.
// Fitted against the response PYTHIAHYDJET_response_DiJet_pThat-15_mu12_pTmu-15_tight_vzReweight_hiBinReweight_hiBinShift-10_leadingXjetDumpFilter_jetTrkMaxFilter_removeHYDJETjet0p35CutOnGen_weightCut_2026-2-18_muTaggedJetsNoTrigger.root
// (jet-branch muon tag); check the rescan's reweighted reco against the data and
// iterate if it does not match.
#include <cmath>
#include <algorithm>
const double leadMuTagEW_s[5] = {0., -0.573244, -0.348561, 0.235862, 0.164190};   // index = nominal class (1 = 0-10% ... 4 = 50-80%)
const double leadMuTagEW_t[5] = {0., 0.000000, 0.000000, 0.000000, 0.000000};
const double leadMuTagEW_ptLo = 20.0, leadMuTagEW_ptHi = 300.0;
inline double leadMuTagEventWeight(int nominalClass, double pt){
  if(nominalClass < 1 || nominalClass > 4 || pt <= 0.) return 1.;
  const double l = std::log(std::min(leadMuTagEW_ptHi, std::max(leadMuTagEW_ptLo, pt))/100.);
  return std::exp((leadMuTagEW_s[nominalClass] + leadMuTagEW_t[nominalClass]*l)*l);
}
