#pragma once
// Muon reco+ID efficiency per 10% centrality class.
// GENERATED by src/muonReconstructionEfficiencyCalculator/muonRecoEfficiency_10pctBins.C -- do not hand-edit.
//
// Interpolated from the FOUR measured PYTHIAHYDJET classes to the
// nine class centres; it is not a fine-binned measurement. See the
// macro header for what that would require. The last two classes are
// held flat beyond the last measured centre.
const double muonRecoEff10[9] = {0.8674, 0.8938, 0.9266, 0.9659, 0.9840, 0.9809, 0.9778, 0.9778, 0.9778};
const double muonRecoEff10Err[9] = {0.0264, 0.0163, 0.0156, 0.0100, 0.0095, 0.0089, 0.0127, 0.0127, 0.0127};
